Add sentence suggesting that Issuer information should be validated by the Receiver
openid/sharedsignals pull request #174
Opened 2024-05-24 14:25 UTC by FragLegs

There are three problems mentioned in Issue #166:

1) We need to add language that suggests the Receiver validate the Issuer value before doing discovery. This PR addresses that.

2) We need to add TLS restriction to the stream management endpoints. PR #173 addresses that.

3) We need to restrict delivery methods to only secure options. That is already done by the fact that the Stream Configuration metadata's `delivery.method` field can only be one of `push` or `poll`.

2024-05-24 20:48 UTC, tulshi approved these changes

2024-05-26 17:20 UTC, timcappalli requested changes

2024-05-26 17:20 UTC, timcappalli commented on openid-sharedsignals-framework-1_0.md
> +trusted source and uses the https scheme.
```suggestion
trusted source and uses the `https` scheme.
```

2024-06-04 17:10 UTC, tulshi approved these changes

2024-06-06 18:52 UTC, timcappalli approved these changes

2024-06-06 18:53 UTC, merged