For vote
openid/sharedsignals pull request #185
Opened 2024-06-14 21:39 UTC by tulshi

Renamed caep spec as per request from Michael Jones at the time of ID-2

2024-06-14 22:12 UTC, appsdesh requested changes
Please update `spec_version`  to 03 from the SSF configuration metadata

2024-06-14 22:59 UTC, tulshi commented
> Please update `spec_version` to 03 in the SSF configuration metadata

Updated (even though they are examples)

2024-06-14 23:02 UTC, appsdesh approved these changes

2024-06-17 12:28 UTC, timcappalli approved these changes

2024-06-17 14:39 UTC, merged