IP Addresses as a format
openid/sharedsignals pull request #206
Opened 2024-09-20 22:14 UTC by appsdesh

IP Addresses as a format

Closes #201

2024-09-24 16:18 UTC, FragLegs requested changes

2024-09-24 16:18 UTC, FragLegs commented on openid-sharedsignals-framework-1_0.md
> +> REQUIRED. The array of IP addresses of the subject as observed by the Transmitter. The value MUST be in the format of an array of strings, each one of which represents the RFC 4001 [RFC4001] string
You need to add RFC4001 as a reference. Do this at the top of the document by adding `RFC4001:` on line 105.

2024-09-30 12:28 UTC, timcappalli commented on openid-sharedsignals-framework-1_0.md
> +    "ips": ["10.29.37.75", "98.27.134.237"]
```suggestion
    "ips": ["203.0.113.75", "2001:0db8:e700:37a7:4cd4::b868"]
```
For IPv4 addresses, it is best practice to use allocated example IP ranges (RFC5737). We should also have an IPv6 address in the example (RFC3849).

The IPv6 example uses common shorthand with the double colon. One question is whether we should allow that or require expansion. No opinion.

2024-10-08 17:14 UTC, timcappalli commented on openid-sharedsignals-framework-1_0.md
> +    "ips": ["10.29.37.75", "98.27.134.237"]
Change of opinion: we should require expanded ones. @timcappalli to find official term (could be "uncompressed", "fully expanded", or "unabbreviated": https://www.ciscopress.com/articles/article.asp?p=2803866)

2024-10-08 call: loose consensus on this

2025-02-25 18:47 UTC, appsdesh commented
Old branch, can't bring it to latest due to Github perms. Continue here https://github.com/openid/sharedsignals/pull/237

2025-02-25 18:47 UTC, closed without merging