Update make instructions and add clarifications
openid/sharedsignals pull request #57
Opened 2023-05-08 13:39 UTC by FragLegs

Adds clarifications to the spec to address Issues #32 and #55

2023-06-07 17:13 UTC, tulshi reviewed
Added a few suggestions inline.

2023-07-13 16:32 UTC, timcappalli requested changes

2023-07-13 16:32 UTC, timcappalli commented on openid-sharedsignals-framework-1_0.md
> +properties will be ignored by the Transmitter. The `events_delivered` property,
should this be "MUST be ignored by the Transmitter"?

2023-07-18 16:06 UTC, timcappalli approved these changes

2023-07-18 16:11 UTC, merged