removed output files. They are now available through the WG website a…
openid/sharedsignals pull request #90
Opened 2023-07-31 20:10 UTC by tulshi

…t: https://openid.net/wg/sharedsignals/specifications/

2023-07-31 20:13 UTC, appsdesh approved these changes
Thank you for doing this!

2023-07-31 20:57 UTC, timcappalli approved these changes

2023-07-31 21:02 UTC, FragLegs requested changes
Can we also add these files to .gitignore in case someone follows the instructions in the README? Maybe also update the README.

2023-08-01 00:23 UTC, FragLegs approved these changes
Awesome!

2023-08-01 00:26 UTC, merged